_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 55
                - 105
            "2":
                - 55
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.8
            "8":
                - 1
                - 5
                - 12
            "12": 0.19.8
            "13": linux-x86_64
architecture:
    value: CNN
dataset:
    value: TinyImageNet
epochs:
    value: 10
learning_rate:
    value: 0.01
